apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: new-ingress-controller
  namespace: openshift-ingress-operator
spec:
  domain: extra.df-rosa-1.2wi6.p1.openshiftapps.com
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
