apiVersion: v1
baseDomain: freesedevelopment.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: 
    aws: 
      type: t3.xlarge
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: 
    aws: 
      type: t3.xlarge
  replicas: 3
metadata:
  creationTimestamp: null
  name: ocp4-test
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-2
publish: External
pullSecret: '<pull-secret>'
sshKey: |
  <public-key>
